// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, prefix, api_key, user_id, permissions, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, prefix, api_key, user_id, permissions, expires_at
`

type CreateAPIKeyParams struct {
	Name        string             `json:"name"`
	Prefix      string             `json:"prefix"`
	ApiKey      string             `json:"api_key"`
	UserID      int32              `json:"user_id"`
	Permissions []string           `json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type CreateAPIKeyRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Prefix      string             `json:"prefix"`
	ApiKey      string             `json:"api_key"`
	UserID      int32              `json:"user_id"`
	Permissions []string           `json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.Prefix,
		arg.ApiKey,
		arg.UserID,
		arg.Permissions,
		arg.ExpiresAt,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.ApiKey,
		&i.UserID,
		&i.Permissions,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys where id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, id)
	return err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, prefix, api_key, user_id, permissions, expires_at, created_at
FROM api_keys
WHERE user_id = $1
`

type ListAPIKeysRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Prefix      string             `json:"prefix"`
	ApiKey      string             `json:"api_key"`
	UserID      int32              `json:"user_id"`
	Permissions []string           `json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, userID int32) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.ApiKey,
			&i.UserID,
			&i.Permissions,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
