// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IpAddress string             `json:"ip_address"`
	UserAgent string             `json:"user_agent"`
}

type User struct {
	ID            int32              `json:"id"`
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	PasswordHash  []byte             `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
