// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Prefix      string             `json:"prefix"`
	ApiKey      string             `json:"api_key"`
	UserID      int32              `json:"user_id"`
	Permissions []string           `json:"permissions"`
	Metadata    []byte             `json:"metadata"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            int32              `json:"id"`
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	PasswordHash  []byte             `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
